export let countries = [
  {
    id: 1,
    country: "Afghanistan",
    currency: "Afghanistani Afghani",
    code: "AFN",
    symbol: "؋",
  },
  {
    id: 2,
    country: "Armenia",
    currency: "Armenian Dram",
    code: "AMD",
    symbol: "դր",
  },
  {
    id: 3,
    country: "Azerbaijan",
    currency: "Azerbaijani Manat",
    code: "AZN",
    symbol: "₼",
  },
  {
    id: 4,
    country: "Bahrain",
    currency: "Bahraini Dinar",
    code: "BHD",
    symbol: ".د.ب",
  },
  {
    id: 5,
    country: "Bangladesh",
    currency: "Bangladeshi Taka",
    code: "BDT",
    symbol: "৳",
  },
  {
    id: 6,
    country: "Bhutan",
    currency: "Bhutanese Ngultrum",
    code: "BTN",
    symbol: "Nu.",
  },
  {
    id: 7,
    country: "Brunei",
    currency: "Brunei Dollar",
    code: "BND",
    symbol: "$",
  },
  {
    id: 8,
    country: "Cambodia",
    currency: "Cambodian Riel",
    code: "KHR",
    symbol: "៛",
  },
  {
    id: 9,
    country: "China",
    currency: "Chinese Yuan Renminbi",
    code: "CNY",
    symbol: "¥",
  },
  {
    id: 10,
    country: "Cyprus",
    currency: "Cypriot Pound",
    code: "CYP",
    symbol: "£",
  },
  {
    id: 11,
    country: "Georgia",
    currency: "Georgian Lari",
    code: "GEL",
    symbol: "ლ",
  },
  {
    id: 12,
    country: "India",
    currency: "Indian Rupee",
    code: "INR",
    symbol: "₹",
  },
  {
    id: 13,
    country: "Indonesia",
    currency: "Indonesian Rupiah",
    code: "IDR",
    symbol: "Rp",
  },
  {
    id: 14,
    country: "Iran",
    currency: "Iranian Rial",
    code: "IRR",
    symbol: "﷼",
  },
  {
    id: 15,
    country: "Iraq",
    currency: "Iraqi Dinar",
    code: "IQD",
    symbol: "ع.د ",
  },
  {
    id: 16,
    country: "Israel",
    currency: "Israeli New Sheqel",
    code: "ILS",
    symbol: "₪",
  },
  {
    id: 17,
    country: "Japan",
    currency: "Japanese Yen",
    code: "JPY",
    symbol: "¥",
  },
  {
    id: 18,
    country: "Jordan",
    currency: "Jordanian Dinar",
    code: "JOD",
    symbol: "د.ا ",
  },
  {
    id: 19,
    country: "Kazakhstan",
    currency: "Kazakhstani Tenge",
    code: "KZT",
    symbol: "лв",
  },
  {
    id: 20,
    country: "Kuwait",
    currency: "Kuwaiti Dinar",
    code: "KWD",
    symbol: "د.ك",
  },
  {
    id: 21,
    country: "Kyrgyzstan",
    currency: "Kyrgyzstani Som",
    code: "KGS",
    symbol: "лв",
  },
  { id: 22, country: "Laos", currency: "Lao Kip", code: "LAK", symbol: "₭" },
  {
    id: 23,
    country: "Lebanon",
    currency: "Lebanese Pound",
    code: "LBP",
    symbol: "£",
  },
  {
    id: 24,
    country: "Malaysia",
    currency: "Malaysian Ringgit",
    code: "MYR",
    symbol: "RM",
  },
  {
    id: 25,
    country: "Maldives",
    currency: "Maldives Rufiyaa",
    code: "MVR",
    symbol: "Rf",
  },
  {
    id: 26,
    country: "Mongolia",
    currency: "Mongolian Tugrik",
    code: "MNT",
    symbol: "₮",
  },
  {
    id: 27,
    country: "Myanmar",
    currency: "(Burma)	Myanmar Kyat",
    code: "MMK",
    symbol: "K",
  },
  {
    id: 28,
    country: "Nepal",
    currency: "Nepalese Rupee",
    code: "NPR",
    symbol: "₨",
  },
  {
    id: 29,
    country: "North Korea",
    currency: "North Korean Won",
    code: "KPW",
    symbol: "₩",
  },
  { id: 30, country: "Oman", currency: "Omani Rial", code: "OMR", symbol: "﷼" },
  {
    id: 31,
    country: "Pakistan",
    currency: "Pakistan Rupee",
    code: "PKR",
    symbol: "₨",
  },
  {
    id: 32,
    country: "Palestine",
    currency: "Jordanian Dinar",
    code: "JOD",
    symbol: "د.ا",
  },
  {
    id: 33,
    country: "Philippines",
    currency: "Philippine Peso",
    code: "PHP",
    symbol: "₱",
  },
  {
    id: 34,
    country: "Qatar",
    currency: "Qatari Riyal",
    code: "QAR",
    symbol: "﷼",
  },
  {
    id: 35,
    country: "Russia",
    currency: "Russian Ruble",
    code: "RUB",
    symbol: "₽",
  },
  {
    id: 36,
    country: "Saudi Arabia",
    currency: "Saudi Arabian Riyal",
    code: "SAR",
    symbol: "﷼",
  },
  {
    id: 37,
    country: "Singapore",
    currency: "Singapore Dollar",
    code: "SGD",
    symbol: "$",
  },
  {
    id: 38,
    country: "South Korea",
    currency: "Korean Won",
    code: "KRW",
    symbol: "₩",
  },
  {
    id: 39,
    country: "Sri Lanka",
    currency: "Sri Lankan Rupee",
    code: "LKR",
    symbol: "₨",
  },
  {
    id: 40,
    country: "Syria",
    currency: "Syrian Pound",
    code: "SYP",
    symbol: "£",
  },
  {
    id: 41,
    country: "Taiwan",
    currency: "New Taiwan Dollar",
    code: "TWD",
    symbol: "NT$",
  },
  {
    id: 42,
    country: "Tajikistan",
    currency: "Tajikistan Somoni",
    code: "TJS",
    symbol: "ЅM",
  },
  {
    id: 43,
    country: "Thailand",
    currency: "Thai Baht",
    code: "THB",
    symbol: "฿",
  },
  {
    id: 44,
    country: "Timor-Leste",
    currency: "United States Dollar",
    code: "USD",
    symbol: "$",
  },
  {
    id: 45,
    country: "Turkey",
    currency: "Turkish New Lira",
    code: "TRY",
    symbol: "₺",
  },
  {
    id: 46,
    country: "Turkmenistan",
    currency: "Turkmenistani Manat",
    code: "TMM",
    symbol: "T",
  },
  {
    id: 47,
    country: "United Arab Emirates (UAE)",
    currency: "United Arab Emirates Dirham",
    code: "AED",
    symbol: "د.إ",
  },
  {
    id: 48,
    country: "Uzbekistan",
    currency: "Uzbekistani Som",
    code: "UZS",
    symbol: "лв",
  },
  {
    id: 49,
    country: "Vietnam",
    currency: "Viet Nam Dong",
    code: "VND",
    symbol: "₫",
  },
  {
    id: 50,
    country: "Yemen",
    currency: "Yemeni Rial",
    code: "YER",
    symbol: "﷼",
  },
  {
    id: 51,
    country: "Algeria",
    currency: "Algerian Dinar",
    code: "DZD",
    symbol: "دج",
  },
  {
    id: 52,
    country: "Angola",
    currency: "Angolan Kwanza",
    code: "AOA",
    symbol: "Kz",
  },
  {
    id: 53,
    country: "Benin",
    currency: "West African CFA",
    code: "XOF",
    symbol: "CFA",
  },
  {
    id: 54,
    country: "Botswana",
    currency: "Botswana Pula",
    code: "BWP",
    symbol: "P",
  },
  {
    id: 55,
    country: "Burkina",
    currency: "Faso	West African CFA",
    code: "XOF",
    symbol: "CFA",
  },
  {
    id: 56,
    country: "Burundi",
    currency: "Burundian Franc",
    code: "BIF",
    symbol: "FBu",
  },
  {
    id: 57,
    country: "Cabo Verde",
    currency: "Cape Verde Escudo",
    code: "CVE",
    symbol: "$",
  },
  {
    id: 58,
    country: "Cameroon",
    currency: "Central African CFA",
    code: "XAF",
    symbol: "FCFA",
  },
  {
    id: 59,
    country: "Central African Republic (CAR)",
    currency: "Central African CFA",
    code: "XAF",
    symbol: "FCFA",
  },
  {
    id: 60,
    country: "Chad",
    currency: "Central African CFA",
    code: "XAF",
    symbol: "FCFA",
  },
  {
    id: 61,
    country: "Comoros",
    currency: "Comorian Franc",
    code: "KMF",
    symbol: "CF",
  },
  {
    id: 62,
    country: "Democratic Republic of the Congo",
    currency: "Congolese franc",
    code: "CDF",
    symbol: "FC",
  },
  {
    id: 63,
    country: "Republic of the Congo",
    currency: "Central African CFA",
    code: "XAF",
    symbol: "FCFA",
  },
  {
    id: 64,
    country: "Cote d'Ivoire",
    currency: "West African CFA",
    code: "XOF",
    symbol: "CFA",
  },
  {
    id: 65,
    country: "Djibouti",
    currency: "Djiboutian Franc",
    code: "DJF",
    symbol: "Fdj",
  },
  { id: 66, country: "Egypt", currency: "Egyptian Pound	EGP", code: "£" },
  {
    id: 67,
    country: "Equatorial Guinea",
    currency: "Central African CFA",
    code: "XAF",
    symbol: "FCFA",
  },
  {
    id: 68,
    country: "Eritrea",
    currency: "Eritrean Nakfa",
    code: "ERN",
    symbol: "ናቕፋ",
  },
  {
    id: 69,
    country: "Ethiopia",
    currency: "Ethiopian Birr",
    code: "ETB",
    symbol: "ብር",
  },
  {
    id: 70,
    country: "Gabon",
    currency: "Central African CFA",
    code: "XAF",
    symbol: "FCFA",
  },
  {
    id: 71,
    country: "Gambia",
    currency: "Gambian Dalasi",
    code: "GMD",
    symbol: "D",
  },
  {
    id: 72,
    country: "Ghana",
    currency: "Ghanaian Cedi",
    code: "GHC",
    symbol: "GH₵",
  },
  {
    id: 73,
    country: "Guinea",
    currency: "Guinean Franc",
    code: "GNF",
    symbol: "FG",
  },
  {
    id: 74,
    country: "Guinea-Bissau",
    currency: "West African CFA",
    code: "XOF",
    symbol: "CFA",
  },
  {
    id: 75,
    country: "Kenya",
    currency: "Kenyan Shilling",
    code: "KES",
    symbol: "KSh,",
  },
  {
    id: 76,
    country: "Lesotho",
    currency: "Lesotho Loti",
    code: "LSL",
    symbol: "L",
  },
  {
    id: 77,
    country: "Liberia",
    currency: "Liberian Dollar",
    code: "LRD",
    symbol: "$",
  },
  {
    id: 78,
    country: "Libya",
    currency: "Libyan Dinar",
    code: "LYD",
    symbol: "ل.د ",
  },
  {
    id: 79,
    country: "Madagascar",
    currency: "Malagasy Ariary",
    code: "MGA",
    symbol: "Ar",
  },
  {
    id: 80,
    country: "Malawi",
    currency: "Malawian Kwacha",
    code: "MWK",
    symbol: "MK",
  },
  {
    id: 81,
    country: "Mali",
    currency: "West African CFA",
    code: "XOF",
    symbol: "CFA",
  },
  {
    id: 82,
    country: "Mauritania",
    currency: "Mauritanian Ouguiya",
    code: "MRO",
    symbol: "UM",
  },
  {
    id: 83,
    country: "Mauritius",
    currency: "Mauritian Rupee",
    code: "MUR",
    symbol: "₨",
  },
  {
    id: 84,
    country: "Morocco",
    currency: "Moroccan Dirham",
    code: "MAD",
    symbol: "DH",
  },
  {
    id: 85,
    country: "Mozambique",
    currency: "Mozambican Metical",
    code: "MZN",
    symbol: "MT",
  },
  {
    id: 86,
    country: "Namibia",
    currency: "Namibian Dollar",
    code: "NAD",
    symbol: "$",
  },
  {
    id: 87,
    country: "Niger",
    currency: "West African CFA",
    code: "XOF",
    symbol: "CFA",
  },
  {
    id: 88,
    country: "Nigeria",
    currency: "Nigerian Naira",
    code: "NGN",
    symbol: "₦",
  },
  {
    id: 89,
    country: "Rwanda",
    currency: "Rwandan Franc",
    code: "RWF",
    symbol: "FRw",
  },
  {
    id: 90,
    country: "Sao Tome and Principe",
    currency: "Sao Tome Dobra",
    code: "STD",
    symbol: "Db",
  },
  {
    id: 91,
    country: "Senegal",
    currency: "West African CFA",
    code: "XOF",
    symbol: "CFA",
  },
  {
    id: 92,
    country: "Seychelles",
    currency: "Seychelles Rupee",
    code: "SCR",
    symbol: "₨",
  },
  {
    id: 93,
    country: "Sierra Leone",
    currency: "Sierra Leonean Leone",
    code: "SLL",
    symbol: "Le",
  },
  {
    id: 94,
    country: "Somalia",
    currency: "Somali Shilling",
    code: "SOS",
    symbol: "S",
  },
  {
    id: 95,
    country: "South Africa",
    currency: "South African Rand",
    code: "ZAR",
    symbol: "R",
  },
  {
    id: 96,
    country: "South Sudan",
    currency: "South Sudanese pound",
    code: "SSP",
    symbol: "£",
  },
  {
    id: 97,
    country: "Sudan",
    currency: "Sudanese pound",
    code: "SDG",
    symbol: "SD",
  },
  {
    id: 98,
    country: "Swaziland",
    currency: "Swazi Lilangeni",
    code: "SZL",
    symbol: "E",
  },
  {
    id: 99,
    country: "Tanzania",
    currency: "Tanzanian Shilling",
    code: "TZS",
    symbol: "TSh",
  },
  {
    id: 100,
    country: "Togo",
    currency: "West African CFA",
    code: "XOF",
    symbol: "CFA",
  },
  {
    id: 101,
    country: "Tunisia",
    currency: "Tunisian Dinar",
    code: "TND",
    symbol: "د.ت",
  },
  {
    id: 102,
    country: "Uganda",
    currency: "Ugandan Shilling",
    code: "UGX",
    symbol: "USh",
  },
  {
    id: 103,
    country: "Zambia",
    currency: "Zambian Kwacha",
    code: "ZMK",
    symbol: "ZK",
  },
  {
    id: 104,
    country: "Zimbabwe",
    currency: "Zimbabwean Dollar",
    code: "ZWD",
    symbol: "$",
  },
  {
    id: 105,
    country: "Albania",
    currency: "Albanian Lek",
    code: "ALL",
    symbol: "Lek",
  },
  {
    id: 106,
    country: "Andorra",
    currency: "European Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    id: 107,
    country: "Armenia",
    currency: "Armenian Dram",
    code: "AMD",
    symbol: "դր.",
  },
  {
    id: 108,
    country: "Austria",
    currency: "European Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    id: 109,
    country: "Azerbaijan",
    currency: "Azerbaijani Manat",
    code: "AZN",
    symbol: "₼",
  },
  {
    id: 110,
    country: "Belarus",
    currency: "Belarusian Ruble",
    code: "BYR",
    symbol: "Br",
  },
  {
    id: 111,
    country: "Belgium",
    currency: "European Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    id: 112,
    country: "Bosnia and Herzegovina",
    currency: "Bosnia-Herzegovina Convertible Mark",
    code: "BAM",
    symbol: "KM",
  },
  {
    id: 113,
    country: "Bulgaria",
    currency: "Bulgarian Lev",
    code: "BGN",
    symbol: "лв",
  },
  {
    id: 114,
    country: "Croatia",
    currency: "Croatian Kuna",
    code: "HRK",
    symbol: "kn",
  },
  {
    id: 115,
    country: "Cyprus",
    currency: "Cypriot Pound",
    code: "CYP",
    symbol: "£",
  },
  {
    id: 116,
    country: "Czech Republic",
    currency: "Czech Koruna",
    code: "CZK",
    symbol: "Kč",
  },
  {
    id: 117,
    country: "Denmark",
    currency: "Danish Krone",
    code: "DKK",
    symbol: "kr.",
  },
  {
    id: 118,
    country: "Estonia",
    currency: "Estonian Kroon",
    code: "EEK",
    symbol: "EEK",
  },
  {
    id: 119,
    country: "Finland",
    currency: "European Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    id: 120,
    country: "France",
    currency: "European Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    id: 121,
    country: "Georgia",
    currency: "Georgian Lari",
    code: "GEL",
    symbol: "ლ",
  },
  {
    id: 122,
    country: "Germany",
    currency: "European Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    id: 123,
    country: "Greece",
    currency: "European Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    id: 124,
    country: "Hungary",
    currency: "Hungarian Forint",
    code: "HUF",
    symbol: "Ft",
  },
  {
    id: 125,
    country: "Iceland",
    currency: "Icelandic Krona",
    code: "ISK",
    symbol: "kr",
  },
  {
    id: 126,
    country: "Ireland",
    currency: "European Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    id: 127,
    country: "Italy",
    currency: "European Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    id: 128,
    country: "Kazakhstan",
    currency: "Kazakhstani Tenge",
    code: "KZT",
    symbol: "лв",
  },
  { id: 129, country: "Kosovo", currency: "Euro", code: "EUR", symbol: "€" },
  {
    id: 130,
    country: "Latvia",
    currency: "Latvian Lats",
    code: "LVL",
    symbol: "Ls",
  },
  {
    id: 131,
    country: "Liechtenstein",
    currency: "Swiss Franc",
    code: "CHF",
    symbol: "CHF",
  },
  {
    id: 132,
    country: "Lithuania",
    currency: "Lithuanian Litas",
    code: "LTL",
    symbol: "Lt",
  },
  {
    id: 133,
    country: "Luxembourg",
    currency: "European Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    id: 134,
    country: "Macedonia (FYROM)",
    currency: "Macedonian Denar",
    code: "MKD",
    symbol: "ден",
  },
  {
    id: 135,
    country: "Malta",
    currency: "Maltese Lira",
    code: "MTL",
    symbol: "₤",
  },
  {
    id: 136,
    country: "Moldova",
    currency: "Moldovan Leu",
    code: "MDL",
    symbol: "L",
  },
  {
    id: 137,
    country: "Monaco",
    currency: "European Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    id: 138,
    country: "Montenegro",
    currency: "European Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    id: 139,
    country: "Netherlands",
    currency: "European Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    id: 140,
    country: "Norway",
    currency: "Norwegian Krone",
    code: "NOK",
    symbol: "kr",
  },
  {
    id: 141,
    country: "Poland",
    currency: "Polish Zloty",
    code: "PLN",
    symbol: "zł",
  },
  {
    id: 142,
    country: "Portugal",
    currency: "European Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    id: 143,
    country: "Romania",
    currency: "Romanian Leu",
    code: "RON",
    symbol: "lei",
  },
  {
    id: 144,
    country: "Russia",
    currency: "Russian Ruble",
    code: "RUB",
    symbol: "₽",
  },
  {
    id: 145,
    country: "San Marino",
    currency: "European Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    id: 146,
    country: "Serbia",
    currency: "Serbian Dinar",
    code: "RSD",
    symbol: "Дин.",
  },
  {
    id: 147,
    country: "Slovakia",
    currency: "Slovak Koruna",
    code: "SKK",
    symbol: "Sk",
  },
  {
    id: 148,
    country: "Slovenia",
    currency: "European Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    id: 149,
    country: "Spain",
    currency: "European Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    id: 150,
    country: "Sweden",
    currency: "Swedish Krona",
    code: "SEK",
    symbol: "kr",
  },
  {
    id: 151,
    country: "Switzerland",
    currency: "Swiss Franc",
    code: "CHF",
    symbol: "CHF",
  },
  {
    id: 152,
    country: "Turkey",
    currency: "Turkish New Lira",
    code: "TRY",
    symbol: "₺",
  },
  {
    id: 153,
    country: "Ukraine",
    currency: "Ukrainian Hryvnia",
    code: "UAH",
    symbol: "₴",
  },
  {
    id: 154,
    country: "United Kingdom (UK)",
    currency: "United Kingdom Pound Sterling",
    code: "GBP",
    symbol: "£",
  },
  {
    id: 155,
    country: "Vatican City (Holy See)",
    currency: "European Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    id: 156,
    country: "Antigua and Barbuda",
    currency: "East Caribbean Dollar",
    code: "XCD",
    symbol: "$",
  },
  {
    id: 157,
    country: "Bahamas",
    currency: "Bahamian Dollar",
    code: "BSD",
    symbol: "$",
  },
  {
    id: 158,
    country: "Barbados",
    currency: "Barbados Dollar",
    code: "BBD",
    symbol: "$",
  },
  {
    id: 159,
    country: "Belize",
    currency: "Belize Dollar",
    code: "BZD",
    symbol: "BZ$",
  },
  {
    id: 160,
    country: "Canada",
    currency: "Canadian Dollar",
    code: "CAD",
    symbol: "$",
  },
  {
    id: 161,
    country: "Costa Rica",
    currency: "Costa Rican Colon",
    code: "CRC",
    symbol: "₡",
  },
  {
    id: 162,
    country: "Cuba",
    currency: "Cuban Convertible Peso",
    code: "CUC",
    symbol: "$",
  },
  {
    id: 163,
    country: "Dominica",
    currency: "East Caribbean Dollar",
    code: "XCD",
    symbol: "$",
  },
  {
    id: 164,
    country: "Dominican Republic",
    currency: "Dominican Peso",
    code: "DOP",
    symbol: "RD$",
  },
  {
    id: 165,
    country: "El Salvador",
    currency: "United States Dollar",
    code: "USD",
    symbol: "$",
  },
  {
    id: 166,
    country: "Grenada",
    currency: "East Caribbean Dollar",
    code: "XCD",
    symbol: "$",
  },
  {
    id: 167,
    country: "Guatemala",
    currency: "Guatemalan Quetzal",
    code: "GTQ",
    symbol: "Q",
  },
  {
    id: 168,
    country: "Haiti",
    currency: "Haitian Gourde",
    code: "HTG",
    symbol: "G",
  },
  {
    id: 169,
    country: "Honduras",
    currency: "Honduran Lempira",
    code: "HNL",
    symbol: "	L",
  },
  {
    id: 170,
    country: "Jamaica",
    currency: "Jamaican Dollar",
    code: "JMD",
    symbol: "J$",
  },
  {
    id: 171,
    country: "Mexico",
    currency: "Mexican Peso",
    code: "MXN",
    symbol: "$",
  },
  {
    id: 172,
    country: "Nicaragua",
    currency: "Nicaraguan Córdoba",
    code: "NIO",
    symbol: "C$",
  },
  {
    id: 173,
    country: "Panama",
    currency: "Panamanian Balboa",
    code: "PAB",
    symbol: "B/.",
  },
  {
    id: 174,
    country: "Saint Kitts and Nevis",
    currency: "East Caribbean Dollar",
    code: "XCD",
    symbol: "$",
  },
  {
    id: 175,
    country: "Saint Lucia",
    currency: "East Caribbean Dollar",
    code: "XCD",
    symbol: "$",
  },
  {
    id: 176,
    country: "Saint Vincent and the Grenadines",
    currency: "East Caribbean Dollar",
    code: "XCD",
    symbol: "$",
  },
  {
    id: 177,
    country: "Trinidad and Tobago",
    currency: "Trinidad and Tobago Dollar",
    code: "TTD",
    symbol: "TT$",
  },
  {
    id: 178,
    country: "United States of America (USA)",
    currency: "United States Dollar",
    code: "USD",
    symbol: "$",
  },
  {
    id: 179,
    country: "Argentina",
    currency: "Argentine Peso",
    code: "ARS",
    symbol: "$",
  },
  {
    id: 180,
    country: "Bolivia",
    currency: "Bolivian Boliviano",
    code: "BOB",
    symbol: "$b",
  },
  {
    id: 181,
    country: "Brazil",
    currency: "Brazilian Real",
    code: "BRL",
    symbol: "R$",
  },
  {
    id: 183,
    country: "Colombia",
    currency: "Colombian Peso",
    code: "COP",
    symbol: "$",
  },
  {
    id: 182,
    country: "Chile",
    currency: "Peso",
    code: "CLP",
    symbol: "$",
  },
  {
    id: 184,
    country: "Ecuador",
    currency: "United States Dollar",
    code: "USD",
    symbol: "$",
  },
  {
    id: 185,
    country: "Guyana",
    currency: "Dollar",
    code: "GYD",
    symbol: "$",
  },
  {
    id: 186,
    country: "Paraguay",
    currency: "Paraguay Guarani",
    code: "PYG",
    symbol: "Gs",
  },
  {
    id: 187,
    country: "Peru",
    currency: "Peruvian Nuevo Sol",
    code: "PEN",
    symbol: "S/.",
  },
  {
    id: 188,
    country: "Suriname",
    currency: "Suriname Dollar",
    code: "SRD",
    symbol: "$",
  },
  {
    id: 189,
    country: "Uruguay",
    currency: "Uruguayan peso",
    code: "UYU",
    symbol: "$U",
  },
  {
    id: 190,
    country: "Venezuela",
    currency: "Venezuelan Bolivar",
    code: "VEF",
    symbol: "Bs",
  },
  {
    id: 191,
    country: "Australia",
    currency: "Australian Dollar",
    code: "AUD",
    symbol: "$",
  },
  {
    id: 192,
    country: "Fiji",
    currency: "Fiji Dollar",
    code: "FJD",
    symbol: "$",
  },
  {
    id: 193,
    country: "Kiribati",
    currency: "Australian Dollar",
    code: "AUD",
    symbol: "$",
  },
  {
    id: 194,
    country: "Marshall Islands",
    currency: "United States Dollar",
    code: "USD",
    symbol: "$",
  },
  {
    id: 195,
    country: "Micronesia",
    currency: "United States Dollar",
    code: "USD",
    symbol: "$",
  },
  {
    id: 196,
    country: "Nauru",
    currency: "Australian Dollar",
    code: "AUD",
    symbol: "$",
  },
  {
    id: 197,
    country: "New Zealand",
    currency: "New Zealand Dollar",
    code: "NZD",
    symbol: "$",
  },
  {
    id: 198,
    country: "Palau",
    currency: "United States Dollar",
    code: "USD",
    symbol: "$",
  },
  {
    id: 199,
    country: "Papua New Guinea",
    currency: "Papua New Guinea Kina",
    code: "PGK",
    symbol: "K",
  },
  {
    id: 200,
    country: "Samoa",
    currency: "Samoan Tala",
    code: "WST",
    symbol: "WS$",
  },
  {
    id: 201,
    country: "Solomon Islands",
    currency: "Solomon Islands Dollar",
    code: "SBD",
    symbol: "$",
  },
  {
    id: 202,
    country: "Tonga",
    currency: "Tongan Pa'Anga",
    code: "TOP",
    symbol: "T$",
  },
  {
    id: 203,
    country: "Tuvalu",
    currency: "Australian Dollar",
    code: "AUD",
    symbol: "$",
  },
  {
    id: 204,
    country: "Vanuatu",
    currency: "Vanuatu Vatu",
    code: "VUV",
    symbol: "VT",
  },
];
